name: MasterDeployCI
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Packages
      run: yarn
    - name: Deploy to GH Pages
      run: yarn deploy
    - name: Updating Domain
      run: echo "Update domain"